google/marl

- CMakeLists.txt
- README.md
- kokoro/linux/presubmit.sh
- kokoro/macos/presubmit.sh
- kokoro/windows/presubmit.bat
Also don't default to building tests.
> Update README.md to include build instructions

- CMakeLists.txt
Test with https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/marl_examples on:
* x86-windows
* x64-windows-static
* x64-linux (Ubuntu 19.04)
> CMake: Add install target

- src/scheduler.cpp
- src/scheduler_test.cpp
> Scheduler: Don't work-steal on the single threaded workers.

- BUILD.bazel
- kokoro/linux/presubmit.sh
- kokoro/macos/presubmit.sh
- kokoro/windows/presubmit.bat
> Kokoro: Add bazel presubmits

- include/marl/blockingcall.h
- src/blockingcall_test.cpp
Works around [this GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41933)
> blocking_call: Workaround for gcc bug with parameter packs

- src/memory.cpp
> Implement page-based functions for Fuchsia

- include/marl/conditionvariable.h
- include/marl/event.h
- include/marl/scheduler.h
- src/event_test.cpp
- src/scheduler.cpp
Implement yields with timeouts, wait_for() / wait_until()
Add Event::any()
> Implement yields with timeouts, add Event::any()

- CMakeLists.txt
- README.md
- examples/BUILD.bazel
- examples/fractal.cpp
- examples/hello_task.cpp
- examples/primes.cpp
Also clean up example `main` signatures.
> Add new 'hello task' example, add to README.md

- docs/imgs/worker_run_mtw.svg
- docs/imgs/worker_run_stw.svg
- docs/imgs/worker_rununtilidle.svg
- docs/imgs/worker_spinforwork.svg
- docs/imgs/worker_suspend.svg
- docs/imgs/worker_waitforwork.svg
- docs/scheduler.md
Describes the implementation, not the usage.
> Docs: Add documentation for marl::Scheduler.

- src/osfiber_asm_arm.S
Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1058107
> arm: Annotate marl_fiber_swap as type %function

- src/thread.cpp
We previously rolled our own `join()` implementation using a `finished` signal via a `condition_variable`, but there was a race condition here between the mutex being unlocked, the thread's stack being freed and the thread returning.
The original implementation of this actually used `WaitForSingleObject()`, but an issue required me to rework this. This no longer appears to be a problem, so switch back.
> Thread: Use WaitForObject for Thread::join()

- src/event_bench.cpp
- src/marl_bench.h
Benchmarks alternating execution of two tasks.
> Benchmarks: Add EventBaton

- include/marl/conditionvariable.h
- include/marl/containers.h
- include/marl/event.h
- include/marl/memory.h
- include/marl/pool.h
- include/marl/waitgroup.h
- src/containers_test.cpp
Provides substantial performance improvements.
> Add marl::containers::list, use for marl::ConditionVariable

- include/marl/scheduler.h
- include/marl/task.h
- src/event_bench.cpp
- src/scheduler.cpp
These changes can offer up to 4.5x speed improvements.
> More optimizations for the patterns seen in EventBaton benchmark

- CMakeLists.txt
I'm not sure how this built for me locally, nor how it passed the presubmits, but AFAICT, this is necessary.
> CMake: Bump min version + include(CheckCXXSourceCompiles)

- README.md
- examples/hello_task.cpp
Cute, but unintentional. I'm blind to this sort of thing.
> Fix stupid typo in front page code samples.

- include/marl/parallelize.h
Execute the first function on the calling thread instead of making the fiber immediately block on the wait group.
There's a chance that the other functions may have finished by the time the first function finishes, entirely avoiding a fiber switch.
> Optimization for marl::parallelize

- include/marl/deprecated.h
- include/marl/scheduler.h
- src/scheduler.cpp
> Add Scheduler::Config and deprecate old [gs]etters

- README.md
FreeBSD added in #135
iOS minor fixes in #137
Fixes: #126
> README: Add FreeBSD and iOS to the list of OSes

- kokoro/macos/build.sh
- kokoro/macos/presubmit.sh
- kokoro/macos/release.sh
- kokoro/release/linux-x64-dbg/release.cfg
- kokoro/release/linux-x64-rel/release.cfg
- kokoro/release/macos-x64-dbg/release.cfg
- kokoro/release/macos-x64-rel/release.cfg
- kokoro/release/windows-x64-dbg/release.cfg
- kokoro/release/windows-x64-rel/release.cfg
- kokoro/ubuntu/release.sh
- kokoro/windows/presubmit.bat
- kokoro/windows/release.bat
Remove the single continuous build config. It doesn't give us what we need.
Includes lots build config file refactoring.
Windows batch files are duplicated for presubmit and release. I'll try and consolidate them later.
> Kokoro: Add release configs

- license-checker.cfg
Update of the license checker changes the rules on this type of license
> Update license checker config

- include/marl/memory.h
Very small PR, was just looking through the code and found this.
> changed alignemt to alignment (spelling mistake)

- .gitignore
ignore auto generated cmake-build-debug folder (default build directory)
ignore auto generated .idea directory (user specific settings)
> ignore auto generated clion files

- src/osfiber_x64.c
link the issue i created (#199) with the explanation, so people only have to read and not search.
> add explanation of the code

- README.md
- docs/scheduler.md
- include/marl/scheduler.h
- include/marl/thread.h
I was taking a look at the documentation and code and took the opportunity to make a number of non-code fixes.
> non-code fixes in comments and documentation

- CMakeLists.txt
- README.md
- src/osfiber_asm_loongarch64.S
- src/osfiber_asm_loongarch64.h
- src/osfiber_loongarch64.c
Some follow-up cleanups for #215.
> LoongArch fixes

- kokoro/ubuntu/docker.sh
- kokoro/ubuntu/presubmit.sh
- kokoro/ubuntu/release.sh
- src/scheduler.cpp
... as well as `get()`.
Another attempt to fix MSAN false-positives in Chromium.
> Unpoison `bound` on `setBound()`

- src/scheduler_bench.cpp
Fixes compiler errors on more recent toolchains
> Update google benchmark to v1.8.0

- BUILD.bazel
- WORKSPACE
https://github.com/bazelbuild/bazel/issues/8622
> Use @platforms instead of @bazel_tools

- src/osfiber_aarch64.c
Old versions (including the one currently in use in Android) of the HWASan runtime do not support a tagged stack pointer.
Tested by building and running the unittests on aarch64 with
export CFLAGS='-fsanitize=hwaddress -mllvm -hwasan-globals=0'
export CXXFLAGS='-fsanitize=hwaddress -mllvm -hwasan-globals=0'
Globals don't currently work with glibc, so I disabled them.
Verified without this change the unittests crash with a HWASan error.
> Untag memory used for stack

- kokoro/windows/presubmit.bat
- kokoro/windows/release.bat
Google-internal bug crbug.com/388901181
> kokoro: use Python 3.12, CMake 3.31.2
